version: '3'

services:
  database:
    image: postgres:16
    restart: always
    ports:
      - 9432:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=3200"
      - "-c"
      - "shared_buffers=8GB"
      - "-c"
      - "effective_cache_size=10GB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      - "max_parallel_maintenance_workers=2"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "autovacuum_max_workers=8"
    environment:
      POSTGRES_DB: frmwrk
      POSTGRES_USER: frmwrk
      POSTGRES_PASSWORD: frmwrk
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  postgres_data:
    driver: local
